name:                LeGit
version:             0.1.0.0
license:             BSD3
author:              "2021_LeGit"
copyright:           "2021 2021_LeGit"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3
- filepath >= 1.3
- filemanip >= 0.3
- optparse-applicative >= 0.15.1 && < 0.17

library:
  source-dirs: src

executables:
  LeGit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    dependencies:
    - LeGit
